name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      # ✅ usa imagem real que existe no Docker Hub
      image: cypress/browsers:node20.9.0-chrome118-ff118
      options: --user 1001
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - uses: cypress-io/github-action@v6
        with:
          # você pode usar seu script "test" ou rodar direto
          command: npx cypress run --browser chrome --record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
