name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: ${{ github.repository }}:custom-cypress-image
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository }}:custom-cypress-image .
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser chrome --record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
